<form action="/registrar" method="POST">

    <h1>Crie uma conta</h1>

    <input type="text" name="nome" placeholder="Usuário" required>
    <input type="email" name="email" placeholder="Email" required>
    <input type="password" name="senha" placeholder="Senha" required>
    <input type="password" name="confirm" placeholder="Confirme sua senha" required>
    <input type="submit" value="Criar Conta">

    <?php if (!empty($feedback)): ?>
        <p class="msg-<?=$tipo?>"><?= $feedback ?></p>
    <?php endif; ?>
</form>

<div class="logo">
    <a href="/"><img src="/img/logo.png" alt="Foto de perfil"></a>
</div>