<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FutQuiz</title>
    <link rel="stylesheet" href="/css/quiz.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" />
</head>

<body>

    <header>
        <div class="logo">
            <a href="/usuario"><img src="/img/logo.png" alt="FutQuiz Logo"></a>
        </div>

        <div class="menu-toggle" id="menu-toggle">
            <i class="fa-solid fa-bars"></i>
        </div>

        <nav id="navMenu">
            <a href="/usuario">Usuário</a>
            <a href="/ranking">Ranking</a>
            <a href="/logout">Sair</a>
        </nav>

        <div class="perfil" id="perfilMenu">
            <a href="/usuario"><img src="https://www.nicepng.com/png/detail/933-9332131_profile-picture-default-png.png" alt="Foto de perfil"></a>

            <!-- Nome REAL do usuário logado -->
            <p class="nome-user"><?= $usuario['nome_usuario'] ?? "Usuário" ?></p>
        </div>
    </header>

    <main class="container">

        <div class="infos">
            <h3>Pontuação: <strong id="pontuacao">0</strong></h3>
            <h3>Tempo: <strong id="tempo">15</strong>s</h3>
        </div>

        <div class="pergunta">
            <p><strong id="contador">1/10</strong></p>
            <p><strong>Pergunta:</strong> 
                <span id="texto-pergunta">Carregando...</span>
            </p>
        </div>

        <div class="opcoes">
            <button class="opcao" data-op="A"></button>
            <button class="opcao" data-op="B"></button>
            <button class="opcao" data-op="C"></button>
            <button class="opcao" data-op="D"></button>
        </div>

    </main>

    <footer class="rodape">
        <div class="info-footer">
            <p>FutQuiz &copy; <?= date("Y") ?> - Todos os direitos reservados</p>
            <p>Desenvolvido por <strong><a href="https://github.com/Dieegoo13">Diego</a></strong></p>
        </div>
    </footer>

    <script src="/js/quiz.js"></script>
    <script src="/js/main.js"></script>

</body>

</html>
