<div class="topo">
    <a href="/quiz"><img src="/img/logo.png" alt="Logo do Sistema"></a>
    <h1>Sua Pontuação foi: <?= $pontosGanhos ?> pontos</h1>
</div>

<div class="informacao">
    <p>Acertos: <?= $acertos ?>/10</p>
    <p>Pontos Ganhos: + <?= $pontosGanhos ?></p>
    <p>Pontuação Total: <?= $pontuacaoTotal ?></p>
</div>

<div class="botoes">
    <a href="/quiz">JOGAR NOVAMENTE</a>
    <a href="/ranking">Ranking</a>
    <a href="/usuario">Perfil</a>
</div>