<!DOCTYPE html>
<html lang="pt-BR">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>FutQuiz - Login</title>

    <link rel="stylesheet" href="/css/style.css">
    <link rel="stylesheet" href="/css/login.css">
</head>

<body>

    <div class="container">

        <div class="foto">
            <img src="/img/logo.png" alt="Logo do Sistema">
        </div>

        <?php if (!empty($erro)): ?>
            <div class="msg-erro"><?= $erro ?></div>
        <?php endif; ?>

        <form action="" method="POST">
            <input type="text" name="email" placeholder="Email" required>
            <input type="password" name="senha" placeholder="Senha" required>

            <input type="submit" class="btn-enviar" value="ENTRAR">
        </form>

        <a href="/cadastro">Cadastre-se</a>
    </div>

</body>

</html>